## JavaScript

### 错误拦截

- [try...catch - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch)

有三种形式:

- `try...catch`
- `try...catch...finally`
- `try...finally`

`try...catch`:

```js
try {
  // do something wrong
} catch (error) {
  console.log(error);
}
```

`try...catch...finally`:

```js
try {
  // do something wrong
} catch (error) {
  console.log(error);
} finally {
  // will execute anyway
}
```

省略 `catch`, `try...finally`:

```js
try {
  // do something wrong
} finally {
  console.log("finally");
}
```

可以从 `error` 中解构出 `name` 和 `message`:

```js
try {
  // do something wrong
} catch (error) {
  const { name, message } = error;
  console.log(name, message);
}

try {
  // do something wrong
} catch ({ name, message }) {
  console.log(name, message);
}
```

关于 `JavaScript` 中 `Error Object` 可参考[这里](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)。

- [Error types](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#error_types)
- [Error Instance properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#instance_properties)

省略 `error`:

```js
try {
  // do something wrong
} catch {
  console.log("error");
}
```

### 主动抛出错误

- [throw](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw)

`throw` 语法:

```js
throw expression;
```

直接抛出字符串 `Error`:

```js
throw 'Error';
```

使用构造函数抛出错误:

```js
throw new Error('Error');
throw new RangeError("The argument must be between 0 and 10.");
throw new ReferenceError("Hello", "someFile.js", 10);
throw new SyntaxError("Hello", "someFile.js", 10);
```

## Dart

### 错误拦截

`try...catch`:

```dart
try {
  // do something wrong
} catch (e) {
  print(e);
}
```

`try...catch...finally`:

```dart
try {
  // do something wrong
} catch (e) {
  print(e);
} finally {
  // will execute anyway
}
```

`try...on...catch`:

```dart
try {
  throw FormatException('Expected at least 1 section');
} on FormatException {
  print('FormatException');
}

try {
  throw FormatException('Expected at least 1 section');
} on FormatException catch (e) {
  // 会被捕获
  print('FormatException: $e');
}

try {
  throw TimeoutException('Timed out', Duration(seconds: 1));
} on FormatException catch (e) {
  // 不会被捕获
  print('FormatException: $e');
} on TimeoutException catch (e) {
  // 会被捕获
  print('TimeoutException: $e');
}

try {
  throw TimeoutException('Timed out', Duration(seconds: 1));
} on FormatException catch (e) {
  // 不会被捕获
  print('FormatException: $e');
} on TimeoutException catch (e) {
  // 会被捕获
  print('TimeoutException: $e');
} catch (e) {
  // 不会执行
  print('Error: $e')
} finally {
  // 会执行
  print('finally');
}
```

输出 `exception` 和 `stack trace`:

```dart
try {
  throw Error();
} catch (e, s) {
  print('Exception details:\n $e');
  print('Stack trace:\n $s');
}
```

### 主动抛出错误

#### Exception

- [Exception class](https://api.dart.dev/stable/3.0.2/dart-core/Exception-class.html)

`Exception Implementers`:

- `DeferredLoadException`
- `FormatException`
- `IOException`
- `IsolateSpawnException`
- `NullRejectionException`
- `OSError`
- `TimeoutException`
- `IntegerDivisionByZeroException` @Deprecated("Use UnsupportedError instead")

```dart
throw FormatException('Expected at least 1 section');
throw TimeoutException('Timed out', Duration(seconds: 1));
```

自定义 `Exception`:

```dart
class FooException implements Exception {
  final String? msg;

  const FooException([this.msg]);

  @override
  String toString() => msg ?? 'FooException';
}
```

#### Error

- [Error class](https://api.dart.dev/stable/3.0.2/dart-core/Error-class.html)

`Error Implementers`:

- `AbstractClassInstantiationError`
- `ArgumentError`
- `AssertionError`
- `AsyncError`
- `ConcurrentModificationError`
- `JsonUnsupportedObjectError`
- `NoSuchMethodError`
- `OutOfMemoryError`
- `ParallelWaitError`
- `RemoteError`
- `StackOverflowError`
- `StateError`
- `TypeError`
- `UnimplementedError`
- `UnsupportedError`

```dart
throw Error();
throw AssertionError('Assertion error');
```

自定义 `Error`:

```dart

```

### assert

- [Assert](https://dart.dev/language/error-handling#assert)

在调试阶段可以使用 `assert` 语法:

```dart
assert(<condition>, <optionalMessage>);
```

> [!tip]
> 在生产环境中 `assert` 不会生效。

如:

```dart
assert(child != null);

assert(child != null, 'child: $child can not be null.');
```

## Python